version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: quick-roll-call-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: quick-roll-call-backend
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ORIGIN: http://localhost:5173
      CHOKIDAR_USEPOLLING: 1
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: quick-roll-call-frontend
    command: npm run dev
    environment:
      NODE_ENV: development
      BACKEND_URL: http://backend:5000
      VITE_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: 1
      VITE_ENABLE_SERVER_LOGS: "1"
      VITE_HTTP_TRACE: "0"
      VITE_API_BASE_URL: "/api"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started
