FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/api/components.yaml ./dist/api/components.yaml

ENV NODE_ENV=production \
	PORT=5000

EXPOSE 5000
CMD ["node", "dist/api/server.js"]